
package oracle.iam.ws.sap.ac10.useraccess;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GracIdmUsrAccsReqServices.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class GracIdmUsrAccsReqServicesException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GracIdmUsrAccsReqServicesRfcException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GracIdmUsrAccsReqServicesException(String message, GracIdmUsrAccsReqServicesRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GracIdmUsrAccsReqServicesException(String message, GracIdmUsrAccsReqServicesRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oracle.iam.ws.sap.ac10.useraccess.GracIdmUsrAccsReqServicesRfcException
     */
    public GracIdmUsrAccsReqServicesRfcException getFaultInfo() {
        return faultInfo;
    }

}
