
package oracle.iam.ws.sap.ac10.requeststatus;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GracIdmRequestStatServices.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class GracIdmRequestStatServicesException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GracIdmRequestStatServicesRfcException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GracIdmRequestStatServicesException(String message, GracIdmRequestStatServicesRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GracIdmRequestStatServicesException(String message, GracIdmRequestStatServicesRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oracle.iam.ws.sap.ac10.requeststatus.GracIdmRequestStatServicesRfcException
     */
    public GracIdmRequestStatServicesRfcException getFaultInfo() {
        return faultInfo;
    }

}
