
package oracle.iam.ws.sap.ac10.requeststatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GRAC_REQUEST_STATUS_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GRACREQUESTSTATUSWS {


    /**
     * 
     * @param reqStatus
     * @param msgReturn
     * @param language
     * @param reqNo
     * @throws GracIdmRequestStatServicesException
     */
    @WebMethod(operationName = "GracIdmRequestStatServices")
    @RequestWrapper(localName = "GracIdmRequestStatServices", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.requeststatus.GracIdmRequestStatServices")
    @ResponseWrapper(localName = "GracIdmRequestStatServicesResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.requeststatus.GracIdmRequestStatServicesResponse")
    public void gracIdmRequestStatServices(
        @WebParam(name = "Language", targetNamespace = "")
        String language,
        @WebParam(name = "ReqNo", targetNamespace = "")
        String reqNo,
        @WebParam(name = "MsgReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsApiMessage> msgReturn,
        @WebParam(name = "ReqStatus", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsRsOpRequestList> reqStatus)
        throws GracIdmRequestStatServicesException
    ;

}
