
package oracle.iam.ws.sap.ac10.searchroles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GRAC_SEARCH_ROLES_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GRACSEARCHROLESWS {


    /**
     * 
     * @param roleDesc
     * @param roleOwner
     * @param connectorGroup
     * @param roleSensitivity
     * @param roleName
     * @param applicationType
     * @param landscape
     * @param orgLvl
     * @param functionalArea
     * @param associatedRole
     * @param roleStatus
     * @param action
     * @param roleType
     * @param businessProcess
     * @param profile
     * @param criticalLevel
     * @param approver
     * @param permission
     * @param lastReaffirmDt
     * @param system
     * @param rolesList
     * @param subProcess
     * @param reaffirmPeriod
     * @param msgReturn
     * @param language
     * @param orgVal
     */
    @WebMethod(operationName = "GracIdmRoleSearchServices")
    @RequestWrapper(localName = "GracIdmRoleSearchServices", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.searchroles.GracIdmRoleSearchServices")
    @ResponseWrapper(localName = "GracIdmRoleSearchServicesResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.searchroles.GracIdmRoleSearchServicesResponse")
    public void gracIdmRoleSearchServices(
        @WebParam(name = "Action", targetNamespace = "")
        String action,
        @WebParam(name = "ApplicationType", targetNamespace = "")
        String applicationType,
        @WebParam(name = "Approver", targetNamespace = "")
        String approver,
        @WebParam(name = "AssociatedRole", targetNamespace = "")
        String associatedRole,
        @WebParam(name = "BusinessProcess", targetNamespace = "")
        String businessProcess,
        @WebParam(name = "ConnectorGroup", targetNamespace = "")
        String connectorGroup,
        @WebParam(name = "CriticalLevel", targetNamespace = "")
        String criticalLevel,
        @WebParam(name = "FunctionalArea", targetNamespace = "")
        String functionalArea,
        @WebParam(name = "Landscape", targetNamespace = "")
        String landscape,
        @WebParam(name = "Language", targetNamespace = "")
        String language,
        @WebParam(name = "LastReaffirmDt", targetNamespace = "")
        String lastReaffirmDt,
        @WebParam(name = "OrgLvl", targetNamespace = "")
        String orgLvl,
        @WebParam(name = "OrgVal", targetNamespace = "")
        String orgVal,
        @WebParam(name = "Permission", targetNamespace = "")
        String permission,
        @WebParam(name = "Profile", targetNamespace = "")
        String profile,
        @WebParam(name = "ReaffirmPeriod", targetNamespace = "")
        String reaffirmPeriod,
        @WebParam(name = "RoleDesc", targetNamespace = "")
        String roleDesc,
        @WebParam(name = "RoleName", targetNamespace = "")
        String roleName,
        @WebParam(name = "RoleOwner", targetNamespace = "")
        String roleOwner,
        @WebParam(name = "RoleSensitivity", targetNamespace = "")
        String roleSensitivity,
        @WebParam(name = "RoleStatus", targetNamespace = "")
        String roleStatus,
        @WebParam(name = "RoleType", targetNamespace = "")
        String roleType,
        @WebParam(name = "SubProcess", targetNamespace = "")
        String subProcess,
        @WebParam(name = "System", targetNamespace = "")
        String system,
        @WebParam(name = "MsgReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsApiMessage> msgReturn,
        @WebParam(name = "RolesList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracTWsSrOpRoleList> rolesList);

}
