
package oracle.iam.ws.sap.ac53.requeststatus;

import javax.xml.ws.WebFault;
import oracle.iam.ws.sap.ac53.requeststatus.core.BOException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "getStatus_com.virsa.ae.core.BOException", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSWsd/SAPGRC_AC_IDM_REQUESTSTATUSVi")
public class GetStatusComVirsaAeCoreBOExceptionDoc
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BOException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetStatusComVirsaAeCoreBOExceptionDoc(String message, BOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetStatusComVirsaAeCoreBOExceptionDoc(String message, BOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oracle.iam.ws.sap.ac53.requeststatus.core.BOException
     */
    public BOException getFaultInfo() {
        return faultInfo;
    }

}
