
package oracle.iam.ws.sap.ac53.requeststatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import oracle.iam.ws.sap.ac53.ejbutil.requeststatus.RequestStatusDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_REQUESTSTATUSVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSWsd/SAPGRC_AC_IDM_REQUESTSTATUSVi/document")
@XmlSeeAlso({
    oracle.iam.ws.sap.ac53.requeststatus.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.requeststatus.core.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.ejbutil.requeststatus.ObjectFactory.class
})
public interface SAPGRCACIDMREQUESTSTATUSViDocument {


    /**
     * 
     * @param requestId
     * @param language
     * @return
     *     returns oracle.iam.ws.sap.ac53.ejbutil.requeststatus.RequestStatusDTO
     * @throws GetStatusComVirsaAeCoreBOExceptionDoc
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
    @RequestWrapper(localName = "getStatus", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi", className = "oracle.iam.ws.sap.ac53.requeststatus.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi", className = "oracle.iam.ws.sap.ac53.requeststatus.GetStatusResponse")
    public RequestStatusDTO getStatus(
        @WebParam(name = "requestId", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
        String requestId,
        @WebParam(name = "language", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
        String language)
        throws GetStatusComVirsaAeCoreBOExceptionDoc
    ;

}
