
package oracle.iam.ws.sap.ac10.auditlogs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GRAC_AUDIT_LOGS_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GRACAUDITLOGSWS {


    /**
     * 
     * @param dateTo
     * @param auditLogs
     * @param msgReturn
     * @param language
     * @param requestNumber
     * @param maxHits
     * @param dateFrom
     * @param requestorId
     */
    @WebMethod(operationName = "GracIdmInboundAuditLogs")
    @RequestWrapper(localName = "GracIdmInboundAuditLogs", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.auditlogs.GracIdmInboundAuditLogs")
    @ResponseWrapper(localName = "GracIdmInboundAuditLogsResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.auditlogs.GracIdmInboundAuditLogsResponse")
    public void gracIdmInboundAuditLogs(
        @WebParam(name = "DateFrom", targetNamespace = "")
        String dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "")
        String dateTo,
        @WebParam(name = "Language", targetNamespace = "")
        String language,
        @WebParam(name = "MaxHits", targetNamespace = "")
        Integer maxHits,
        @WebParam(name = "RequestNumber", targetNamespace = "")
        String requestNumber,
        @WebParam(name = "RequestorId", targetNamespace = "")
        String requestorId,
        @WebParam(name = "AuditLogs", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracTApiAuditLogs> auditLogs,
        @WebParam(name = "MsgReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsApiMessage> msgReturn);

}
