
package oracle.iam.ws.sap.ac10.auditlogs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "service", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/D:/ant_grctest_19JUL2012/wsdl/grc10/GRAC_AUDIT_LOGS_WS/GRAC_AUDIT_LOGS_WS.WSDL")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(oracle.iam.ws.sap.ac10.auditlogs.Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = oracle.iam.ws.sap.ac10.auditlogs.Service.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/ant_grctest_19JUL2012/wsdl/grc10/GRAC_AUDIT_LOGS_WS/GRAC_AUDIT_LOGS_WS.WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/ant_grctest_19JUL2012/wsdl/grc10/GRAC_AUDIT_LOGS_WS/GRAC_AUDIT_LOGS_WS.WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICE_WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(SERVICE_WSDL_LOCATION, new QName("urn:sap-com:document:sap:soap:functions:mc-style", "service"));
    }

    /**
     * 
     * @return
     *     returns GRACAUDITLOGSWS
     */
    @WebEndpoint(name = "binding")
    public GRACAUDITLOGSWS getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), GRACAUDITLOGSWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GRACAUDITLOGSWS
     */
    @WebEndpoint(name = "binding")
    public GRACAUDITLOGSWS getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), GRACAUDITLOGSWS.class, features);
    }

}
