
package oracle.iam.ws.sap.ac53.searchroles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import oracle.iam.ws.sap.ac53.ejbutil.searchroles.SearchRolesResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_SEARCHROLESVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESWsd/SAPGRC_AC_IDM_SEARCHROLESVi/document")
@XmlSeeAlso({
    oracle.iam.ws.sap.ac53.ejbutil.searchroles.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.searchroles.ejbutil.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.searchroles.core.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.searchroles.ObjectFactory.class
})
public interface SAPGRCACIDMSEARCHROLESViDocument {


    /**
     * 
     * @param roleDesc
     * @param application
     * @param hitCount
     * @param transactionCode
     * @param subProcess
     * @param locale
     * @param userId
     * @param company
     * @param role
     * @param businessProcess
     * @param functionalArea
     * @param accessType
     * @return
     *     returns oracle.iam.ws.sap.ac53.ejbutil.searchroles.SearchRolesResult
     * @throws GetRolesComVirsaAeCoreBOExceptionDoc
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
    @RequestWrapper(localName = "getRoles", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi", className = "oracle.iam.ws.sap.ac53.searchroles.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi", className = "oracle.iam.ws.sap.ac53.searchroles.GetRolesResponse")
    public SearchRolesResult getRoles(
        @WebParam(name = "application", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String application,
        @WebParam(name = "accessType", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String accessType,
        @WebParam(name = "businessProcess", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String businessProcess,
        @WebParam(name = "subProcess", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String subProcess,
        @WebParam(name = "role", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String role,
        @WebParam(name = "roleDesc", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String roleDesc,
        @WebParam(name = "functionalArea", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String functionalArea,
        @WebParam(name = "company", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String company,
        @WebParam(name = "transactionCode", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String transactionCode,
        @WebParam(name = "userId", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String userId,
        @WebParam(name = "locale", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        String locale,
        @WebParam(name = "hitCount", targetNamespace = "urn:SAPGRC_AC_IDM_SEARCHROLESVi")
        int hitCount)
        throws GetRolesComVirsaAeCoreBOExceptionDoc
    ;

}
