
package oracle.iam.ws.sap.ac53.selectsystem;

import javax.xml.ws.WebFault;
import oracle.iam.ws.sap.ac53.ejbutil.selectsystem.ConfigurationException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "getSystems_com.virsa.ae.ejbutil.selectsystem.ConfigurationException", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd/SAPGRC_AC_IDM_SELECTAPPLICATIONVi")
public class GetSystemsComVirsaAeEjbutilSelectsystemConfigurationExceptionDoc
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConfigurationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetSystemsComVirsaAeEjbutilSelectsystemConfigurationExceptionDoc(String message, ConfigurationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetSystemsComVirsaAeEjbutilSelectsystemConfigurationExceptionDoc(String message, ConfigurationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oracle.iam.ws.sap.ac53.ejbutil.selectsystem.ConfigurationException
     */
    public ConfigurationException getFaultInfo() {
        return faultInfo;
    }

}
