
package oracle.iam.ws.sap.ac53.selectsystem;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SAPGRC_AC_IDM_SELECTAPPLICATION", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd", wsdlLocation = "file:/D:/ant_grctest_19JUL2012/wsdl/grc53/SAPGRC_AC_IDM_SELECTAPPLICATION/main.wsdl")
public class SAPGRCACIDMSELECTAPPLICATION
    extends Service
{

    private final static URL SAPGRCACIDMSELECTAPPLICATION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(oracle.iam.ws.sap.ac53.selectsystem.SAPGRCACIDMSELECTAPPLICATION.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = oracle.iam.ws.sap.ac53.selectsystem.SAPGRCACIDMSELECTAPPLICATION.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/ant_grctest_19JUL2012/wsdl/grc53/SAPGRC_AC_IDM_SELECTAPPLICATION/main.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/ant_grctest_19JUL2012/wsdl/grc53/SAPGRC_AC_IDM_SELECTAPPLICATION/main.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAPGRCACIDMSELECTAPPLICATION_WSDL_LOCATION = url;
    }

    public SAPGRCACIDMSELECTAPPLICATION(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPGRCACIDMSELECTAPPLICATION() {
        super(SAPGRCACIDMSELECTAPPLICATION_WSDL_LOCATION, new QName("urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd", "SAPGRC_AC_IDM_SELECTAPPLICATION"));
    }

    /**
     * 
     * @return
     *     returns SAPGRCACIDMSELECTAPPLICATIONViDocument
     */
    @WebEndpoint(name = "Config1Port_Document")
    public SAPGRCACIDMSELECTAPPLICATIONViDocument getConfig1PortDocument() {
        return super.getPort(new QName("urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd", "Config1Port_Document"), SAPGRCACIDMSELECTAPPLICATIONViDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPGRCACIDMSELECTAPPLICATIONViDocument
     */
    @WebEndpoint(name = "Config1Port_Document")
    public SAPGRCACIDMSELECTAPPLICATIONViDocument getConfig1PortDocument(WebServiceFeature... features) {
        return super.getPort(new QName("urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd", "Config1Port_Document"), SAPGRCACIDMSELECTAPPLICATIONViDocument.class, features);
    }

}
