
package oracle.iam.ws.sap.ac53.selectsystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import oracle.iam.ws.sap.ac53.ejbutil.selectsystem.SystemSelectionResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_SELECTAPPLICATIONVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONWsd/SAPGRC_AC_IDM_SELECTAPPLICATIONVi/document")
@XmlSeeAlso({
    oracle.iam.ws.sap.ac53.selectsystem.ejbutil.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.ejbutil.selectsystem.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.selectsystem.ObjectFactory.class
})
public interface SAPGRCACIDMSELECTAPPLICATIONViDocument {


    /**
     * 
     * @param systemType
     * @param locale
     * @param applicationType
     * @return
     *     returns oracle.iam.ws.sap.ac53.ejbutil.selectsystem.SystemSelectionResult
     * @throws GetSystemsComVirsaAeEjbutilSelectsystemConfigurationExceptionDoc
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi")
    @RequestWrapper(localName = "getSystems", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi", className = "oracle.iam.ws.sap.ac53.selectsystem.GetSystems")
    @ResponseWrapper(localName = "getSystemsResponse", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi", className = "oracle.iam.ws.sap.ac53.selectsystem.GetSystemsResponse")
    public SystemSelectionResult getSystems(
        @WebParam(name = "systemType", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi")
        String systemType,
        @WebParam(name = "applicationType", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi")
        String applicationType,
        @WebParam(name = "locale", targetNamespace = "urn:SAPGRC_AC_IDM_SELECTAPPLICATIONVi")
        String locale)
        throws GetSystemsComVirsaAeEjbutilSelectsystemConfigurationExceptionDoc
    ;

}
