
package oracle.iam.ws.sap.ac53.submitrequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import oracle.iam.ws.sap.ac53.ejbutil.submitrequest.RequestSubmissionResult;
import oracle.iam.ws.sap.ac53.submitrequest.ejbutil.RequestDetailsData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_SUBMITREQUESTVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTWsd/SAPGRC_AC_IDM_SUBMITREQUESTVi/document")
@XmlSeeAlso({
    oracle.iam.ws.sap.ac53.ejbutil.submitrequest.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.submitrequest.ObjectFactory.class,
    oracle.iam.ws.sap.ac53.submitrequest.ejbutil.ObjectFactory.class
})
public interface SAPGRCACIDMSUBMITREQUESTViDocument {


    /**
     * 
     * @param requestDetails
     * @return
     *     returns oracle.iam.ws.sap.ac53.ejbutil.submitrequest.RequestSubmissionResult
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi")
    @RequestWrapper(localName = "getSubmitRequest", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi", className = "oracle.iam.ws.sap.ac53.submitrequest.GetSubmitRequest")
    @ResponseWrapper(localName = "getSubmitRequestResponse", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi", className = "oracle.iam.ws.sap.ac53.submitrequest.GetSubmitRequestResponse")
    public RequestSubmissionResult getSubmitRequest(
        @WebParam(name = "requestDetails", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi")
        RequestDetailsData requestDetails);

}
