
package oracle.iam.ws.sap.ac10.lookup;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "GracIdmLookupServices.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class GracIdmLookupServicesException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GracIdmLookupServicesRfcException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GracIdmLookupServicesException(String message, GracIdmLookupServicesRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GracIdmLookupServicesException(String message, GracIdmLookupServicesRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: oracle.iam.ws.sap.ac10.lookup.GracIdmLookupServicesRfcException
     */
    public GracIdmLookupServicesRfcException getFaultInfo() {
        return faultInfo;
    }

}
