
package oracle.iam.ws.sap.ac10.lookup;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GRAC_LOOKUP_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GRACLOOKUPWS {


    /**
     * 
     * @param landscapeList
     * @param priorityType
     * @param roleSensitivity
     * @param communicationTypeList
     * @param roleSensitivityList
     * @param busSubProcList
     * @param landscape
     * @param roleTypeList
     * @param requestTypeList
     * @param functionArea
     * @param communicationType
     * @param functionAreaList
     * @param roleStatus
     * @param roleType
     * @param busProcList
     * @param omObjectTypeList
     * @param criticalLevelList
     * @param roleStatusList
     * @param itemProvTypeList
     * @param busSubProc
     * @param employeeType
     * @param busProc
     * @param itemProvType
     * @param roleCustomFieldsList
     * @param priorityTypeList
     * @param requestCustomFieldsList
     * @param criticalLevel
     * @param omObjectIdList
     * @param customFieldValues
     * @param phaseList
     * @param requestType
     * @param roleCustomFields
     * @param customFieldDetails
     * @param omObjectValue
     * @param itemProvActionType
     * @param requestCustomFields
     * @param itemProvActionList
     * @param omObjectType
     * @param projectRelease
     * @param employeeTypeList
     * @param language
     * @param phase
     * @param projectReleaseList
     * @throws GracIdmLookupServicesException
     */
    @WebMethod(operationName = "GracIdmLookupServices")
    @RequestWrapper(localName = "GracIdmLookupServices", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.lookup.GracIdmLookupServices")
    @ResponseWrapper(localName = "GracIdmLookupServicesResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "oracle.iam.ws.sap.ac10.lookup.GracIdmLookupServicesResponse")
    public void gracIdmLookupServices(
        @WebParam(name = "BusProc", targetNamespace = "")
        String busProc,
        @WebParam(name = "BusSubProc", targetNamespace = "")
        String busSubProc,
        @WebParam(name = "CommunicationType", targetNamespace = "")
        String communicationType,
        @WebParam(name = "CriticalLevel", targetNamespace = "")
        String criticalLevel,
        @WebParam(name = "CustomFieldValues", targetNamespace = "")
        GracSWsLuIpCustFldVal customFieldValues,
        @WebParam(name = "EmployeeType", targetNamespace = "")
        String employeeType,
        @WebParam(name = "FunctionArea", targetNamespace = "")
        String functionArea,
        @WebParam(name = "ItemProvActionType", targetNamespace = "")
        GracSWsLuIpItmPrvActns itemProvActionType,
        @WebParam(name = "ItemProvType", targetNamespace = "")
        String itemProvType,
        @WebParam(name = "Landscape", targetNamespace = "")
        String landscape,
        @WebParam(name = "Language", targetNamespace = "")
        String language,
        @WebParam(name = "OmObjectType", targetNamespace = "")
        String omObjectType,
        @WebParam(name = "OmObjectValue", targetNamespace = "")
        GracSWsLuIpOmObjectVal omObjectValue,
        @WebParam(name = "Phase", targetNamespace = "")
        String phase,
        @WebParam(name = "PriorityType", targetNamespace = "")
        String priorityType,
        @WebParam(name = "ProjectRelease", targetNamespace = "")
        String projectRelease,
        @WebParam(name = "RequestCustomFields", targetNamespace = "")
        String requestCustomFields,
        @WebParam(name = "RequestType", targetNamespace = "")
        String requestType,
        @WebParam(name = "RoleCustomFields", targetNamespace = "")
        String roleCustomFields,
        @WebParam(name = "RoleSensitivity", targetNamespace = "")
        String roleSensitivity,
        @WebParam(name = "RoleStatus", targetNamespace = "")
        String roleStatus,
        @WebParam(name = "RoleType", targetNamespace = "")
        String roleType,
        @WebParam(name = "BusProcList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpBusProcWrap> busProcList,
        @WebParam(name = "BusSubProcList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpBusSprocWrap> busSubProcList,
        @WebParam(name = "CommunicationTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpCommnTypWrap> communicationTypeList,
        @WebParam(name = "CriticalLevelList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpCritLvlWrap> criticalLevelList,
        @WebParam(name = "CustomFieldDetails", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpCstflValWrap> customFieldDetails,
        @WebParam(name = "EmployeeTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpEmptypeWrap> employeeTypeList,
        @WebParam(name = "FunctionAreaList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpFuncAreaWrap> functionAreaList,
        @WebParam(name = "ItemProvActionList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpItemActnWrap> itemProvActionList,
        @WebParam(name = "ItemProvTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpReqActnWrap> itemProvTypeList,
        @WebParam(name = "LandscapeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpLandscapeWrap> landscapeList,
        @WebParam(name = "OmObjectIdList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpOmObjIdWrap> omObjectIdList,
        @WebParam(name = "OmObjectTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpOmObjtypWrap> omObjectTypeList,
        @WebParam(name = "PhaseList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpPhaseWrap> phaseList,
        @WebParam(name = "PriorityTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpPriorityWrap> priorityTypeList,
        @WebParam(name = "ProjectReleaseList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpPrjRelsWrap> projectReleaseList,
        @WebParam(name = "RequestCustomFieldsList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpCustFldWrap> requestCustomFieldsList,
        @WebParam(name = "RequestTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpReqTypWrap> requestTypeList,
        @WebParam(name = "RoleCustomFieldsList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpCustFldWrap> roleCustomFieldsList,
        @WebParam(name = "RoleSensitivityList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpRoleSensWrap> roleSensitivityList,
        @WebParam(name = "RoleStatusList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpRoleStatWrap> roleStatusList,
        @WebParam(name = "RoleTypeList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<GracSWsLuOpRoleTypeWrap> roleTypeList)
        throws GracIdmLookupServicesException
    ;

}
